A simple machine learning application

In [1]:
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import mglearn
from IPython.display import display

ImportError: 
`load_boston` has been removed from scikit-learn since version 1.2.

The Boston housing prices dataset has an ethical problem: as
investigated in [1], the authors of this dataset engineered a
non-invertible variable "B" assuming that racial self-segregation had a
positive impact on house prices [2]. Furthermore the goal of the
research that led to the creation of this dataset was to study the
impact of air quality but it did not give adequate demonstration of the
validity of this assumption.

The scikit-learn maintainers therefore strongly discourage the use of
this dataset unless the purpose of the code is to study and educate
about ethical issues in data science and machine learning.

In this special case, you can fetch the dataset from the original
source::

    import pandas as pd
    import numpy as np

    data_url = "http://lib.stat.cmu.edu/datasets/boston"
    raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
    data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
    target = raw_df.values[1::2, 2]

Alternative datasets include the California housing dataset and the
Ames housing dataset. You can load the datasets as follows::

    from sklearn.datasets import fetch_california_housing
    housing = fetch_california_housing()

for the California housing dataset and::

    from sklearn.datasets import fetch_openml
    housing = fetch_openml(name="house_prices", as_frame=True)

for the Ames housing dataset.

[1] M Carlisle.
"Racist data destruction?"
<https://medium.com/@docintangible/racist-data-destruction-113e3eff54a8>

[2] Harrison Jr, David, and Daniel L. Rubinfeld.
"Hedonic housing prices and the demand for clean air."
Journal of environmental economics and management 5.1 (1978): 81-102.
<https://www.researchgate.net/publication/4974606_Hedonic_housing_prices_and_the_demand_for_clean_air>


In [2]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()

In [3]:
print('Keys of iris_dataset:\n', iris_dataset.keys())

Keys of iris_dataset:
 dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [4]:
print(iris_dataset['DESCR'][:193] + '\n...')

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, pre
...


In [5]:
print('Target names: ', iris_dataset['target_names'])

Target names:  ['setosa' 'versicolor' 'virginica']


In [6]:
print('Feature names:\n', iris_dataset['feature_names'])

Feature names:
 ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [7]:
print('Type of data: ', type(iris_dataset['data']))

Type of data:  <class 'numpy.ndarray'>


In [8]:
print('Shape of data: ', iris_dataset['data'].shape)

Shape of data:  (150, 4)


In [9]:
print('First five rows of data:\n', iris_dataset['data'][:5])

First five rows of data:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [10]:
print('Type of target: ', type(iris_dataset['target']))

Type of target:  <class 'numpy.ndarray'>


In [11]:
print('Shape of target: ', iris_dataset['target'].shape)

Shape of target:  (150,)


In [12]:
print('Target:\n', iris_dataset['target'])

Target:
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


Training and testing

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    iris_dataset['data'], iris_dataset['target'], random_state = 0)

In [14]:
print('X_train shape: ', X_train.shape)
print('y_train shape: ', y_train.shape)

X_train shape:  (112, 4)
y_train shape:  (112,)


In [15]:
print('X_test shape: ', X_test.shape)
print('y_test shape: ', y_test.shape)

X_test shape:  (38, 4)
y_test shape:  (38,)


In [16]:
iris_dataframe = pd.DataFrame(X_train, columns = iris_dataset.feature_names)

pd.plotting.scatter_matrix(
                            iris_dataframe
                          , c = y_train
                          , figsize = (15, 15)
                          , marker = 'o'
                          , hist_kwds = {'bins': 20}
                          , s = 60
                          , alpha = .8
                          , cmap = mglearn.cm3
                          )

NameError: name 'mglearn' is not defined

The model

In [17]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 1)

In [18]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [19]:
X_new = np.array([[5, 2.9, 1, 0.2]])
print('X_new.shape: ', X_new.shape)

X_new.shape:  (1, 4)


In [20]:
prediction = knn.predict(X_new)
print('Prediction: ', prediction)
print('Predicted target name: ',
     iris_dataset['target_names'][prediction])

Prediction:  [0]
Predicted target name:  ['setosa']


In [21]:
y_pred = knn.predict(X_test)
print('Test set predictions:\n', y_pred)

Test set predictions:
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [22]:
print('Test set score: {:.2f}'.format(np.mean(y_pred == y_test)))

Test set score: 0.97


In [23]:
print('Test set score: {:.2f}'.format(knn.score(X_test, y_test)))

Test set score: 0.97
